spring:
  kafka:
    # streams 相关配置
    streams:
      application-id: test-kafka-stream # 默认取springboot应用名
      # bootstrap-servers: ${KAFKA_HOST:localhost}:${KAFKA_PORT:9092} # 会覆盖 spring.kafka.bootstrap-servers 配置
      auto-startup: true
      properties:
        default:
          key:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde # 序列化key
          value:
            serde: org.apache.kafka.common.serialization.Serdes$StringSerde # 序列化value
          timestamp:
            extractor: org.apache.kafka.streams.processor.WallclockTimestampExtractor
#        spring:
#          json:
#            trusted:
#              packages: com.* # 允许json反序列化的包