server:
  port: 2112
spring:
  application:
    name: springdatajpa
  datasource:
    url: jdbc:mysql://localhost:3306/jpademo?useUnicode=true&characterEncoding=UTF-8&useJDBCCompliantTimezoneShift=true&useLegacyDatetimeCode=false&serverTimezone=Asia/Shanghai&allowMultiQueries=true
    username: root
    password: root
    driver-class-name: com.mysql.cj.jdbc.Driver
  jpa:
    database: MySQL
    # 创建的表的 ENGINE 为 InnoDB
    database-platform: org.hibernate.dialect.MySQL55Dialect
    # 打印出 sql 语句
    show-sql: true
    properties:
      hibernate:
       #解决Hibernate Lazy-Init问题
       enable_lazy_load_no_trans: true
    hibernate:
      ddl-auto: none
      naming:
        physical-strategy: org.springframework.boot.orm.jpa.hibernate.SpringPhysicalNamingStrategy

#spring.jpa.hibernate.ddl-auto 说明：
#  create：每次运行程序时，都会重新创建表，故而数据会丢失
#  create-drop：每次运行程序时会先创建表结构，然后待程序结束时清空表
#  update：每次运行程序，没有表时会创建表，如果对象发生改变会更新表结构，原有数据不会清空，只会更新（推荐使用）
#  validate：运行程序会校验数据与数据库的字段类型是否相同，字段不同会报错
#  none: 禁用DDL处理

#spring.jpa.hibernate.naming.physical-strategy 命名策略
#   PhysicalNamingStrategyStandardImpl  无修改命名
#   SpringPhysicalNamingStrategy 驼峰下划线命名
